<?php
session_start();
require_once '../config/Database.php';
require_once '../classes/Auth.php';
require_once __DIR__ . '/includes/catalogo_cuentas_helpers.php';
$db=(new Database())->getConnection(); $db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);
$auth=new Auth($db); $auth->requireLogin(); ensureAccountingCatalog($db); $message='';
if($_SERVER['REQUEST_METHOD']==='POST'){try{Auth::checkCSRF($_POST['csrf_token']??'');$action=(string)($_POST['action']??'');if($action==='save'){$id=(int)($_POST['id']??0);$code=trim((string)($_POST['codigo']??''));$name=trim((string)($_POST['nombre']??''));$type=in_array($_POST['tipo']??'',['Gasto','Balance'],true)?$_POST['tipo']:'Gasto';if($code===''||$name==='')throw new RuntimeException('El código y el nombre son obligatorios.');if(!preg_match('/^[0-9A-Za-z._-]{2,30}$/',$code))throw new RuntimeException('El código contiene caracteres no permitidos.');$v=[$code,$name,trim((string)($_POST['sinopsis']??'')),$type,!empty($_POST['permite_compras'])?1:0,!empty($_POST['activo'])?1:0];if($id>0){$v[]=$id;$db->prepare('UPDATE ah_catalogo_cuentas SET codigo=?,nombre=?,sinopsis=?,tipo=?,permite_compras=?,activo=? WHERE id=?')->execute($v);}else{$db->prepare("INSERT INTO ah_catalogo_cuentas(codigo,nombre,sinopsis,tipo,permite_compras,activo,orden,fuente) VALUES(?,?,?,?,?,?,9999,'CRUD financiero')")->execute($v);}$message='Cuenta guardada correctamente.';}elseif($action==='toggle'){$db->prepare('UPDATE ah_catalogo_cuentas SET activo=IF(activo=1,0,1) WHERE id=?')->execute([(int)($_POST['id']??0)]);$message='Estado de la cuenta actualizado.';}}catch(Throwable $e){$message=$e->getMessage();}}
$edit=null;if(!empty($_GET['edit'])){$st=$db->prepare('SELECT * FROM ah_catalogo_cuentas WHERE id=?');$st->execute([(int)$_GET['edit']]);$edit=$st->fetch(PDO::FETCH_ASSOC)?:null;}
$accounts=$db->query("SELECT * FROM ah_catalogo_cuentas ORDER BY FIELD(tipo,'Gasto','Balance'),orden,codigo,nombre")->fetchAll(PDO::FETCH_ASSOC);$csrf=Auth::generateCSRF();
function ccH($v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
?>
<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Catálogo contable | Acción Honduras</title><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"><style>
body{font-family:Inter,sans-serif;margin:0;display:flex;min-height:100vh;background:#f8fafc;color:#172033}.main-wrapper{flex:1;min-width:0;padding:30px}.header{margin-bottom:20px}.header h1{margin:0;font-size:1.8rem}.header p{color:#64748b;margin:6px 0}.layout{display:grid;grid-template-columns:minmax(300px,390px) minmax(0,1fr);gap:18px}.card{background:#fff;border:1px solid #dbe4ee;border-radius:14px;padding:20px;box-shadow:0 5px 16px rgba(15,23,42,.035)}.card h2{margin:0 0 16px;font-size:1rem}.field{margin-bottom:13px}.field label{display:block;font-size:.76rem;font-weight:700;margin-bottom:6px;color:#475569}.control{width:100%;box-sizing:border-box;border:1px solid #cbd5e1;border-radius:9px;padding:10px 11px;font:inherit}.check{display:flex;gap:8px;align-items:center;margin:10px 0;font-size:.82rem}.actions{display:flex;gap:8px;margin-top:16px}.btn{display:inline-flex;align-items:center;gap:7px;border:0;border-radius:9px;padding:10px 13px;background:#34859B;color:#fff;text-decoration:none;font:inherit;font-weight:700;cursor:pointer}.btn.secondary{background:#e8eef4;color:#334155}.btn.tiny{padding:6px 8px;font-size:.72rem}.notice{padding:11px 14px;border-radius:9px;background:#e7f6f1;color:#166534;margin-bottom:16px;font-size:.82rem}.table-shell{overflow:auto;max-height:72vh;border:1px solid #dbe4ee;border-radius:10px}table{border-collapse:collapse;width:100%;min-width:850px;font-size:.76rem}th{position:sticky;top:0;background:#edf3f7;padding:10px;text-align:left;z-index:2}td{padding:9px 10px;border-top:1px solid #edf1f5;vertical-align:top}.badge{display:inline-block;padding:3px 7px;border-radius:99px;background:#e8eef4;font-size:.67rem;font-weight:700}.badge.on{background:#dcfae6;color:#087443}.badge.off{background:#fee4e2;color:#b42318}.toolbar{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:12px}.toolbar input,.toolbar select{border:1px solid #cbd5e1;border-radius:8px;padding:9px 10px;font:inherit;font-size:.78rem}@media(max-width:1000px){.layout{grid-template-columns:1fr}.main-wrapper{padding:18px}}
</style></head><body><?php include 'sidebar.php';?><main class="main-wrapper"><header class="header"><h1><i class="fa-solid fa-book-open" style="color:#34859B"></i> Catálogo de cuentas contables</h1><p>Fuente financiera independiente del POA · <?=count($accounts)?> registros</p></header><?php if($message):?><div class="notice"><?=ccH($message)?></div><?php endif;?><div class="layout">
<section class="card"><h2><?=$edit?'Editar cuenta':'Nueva cuenta'?></h2><form method="post"><input type="hidden" name="csrf_token" value="<?=ccH($csrf)?>"><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?=ccH($edit['id']??0)?>"><div class="field"><label>Código</label><input class="control" name="codigo" maxlength="30" required value="<?=ccH($edit['codigo']??'')?>"></div><div class="field"><label>Nombre</label><input class="control" name="nombre" maxlength="255" required value="<?=ccH($edit['nombre']??'')?>"></div><div class="field"><label>Tipo</label><select class="control" name="tipo"><option <?=($edit['tipo']??'Gasto')==='Gasto'?'selected':''?>>Gasto</option><option <?=($edit['tipo']??'')==='Balance'?'selected':''?>>Balance</option></select></div><div class="field"><label>Sinopsis / uso</label><textarea class="control" name="sinopsis" rows="7"><?=ccH($edit['sinopsis']??'')?></textarea></div><label class="check"><input type="checkbox" name="permite_compras" value="1" <?=!$edit||!empty($edit['permite_compras'])?'checked':''?>> Disponible en compras</label><label class="check"><input type="checkbox" name="activo" value="1" <?=!$edit||!empty($edit['activo'])?'checked':''?>> Cuenta activa</label><div class="actions"><button class="btn"><i class="fa-solid fa-floppy-disk"></i> Guardar</button><?php if($edit):?><a class="btn secondary" href="catalogo_cuentas.php">Cancelar</a><?php endif;?></div></form></section>
<section class="card"><h2>Cuentas registradas</h2><div class="toolbar"><input id="search" placeholder="Buscar código, nombre o sinopsis…" style="flex:1;min-width:220px"><select id="type"><option value="">Todos los tipos</option><option>Gasto</option><option>Balance</option></select><select id="state"><option value="">Todos los estados</option><option value="1">Activas</option><option value="0">Inactivas</option></select></div><div class="table-shell"><table data-table-ux="on" data-table-search="off"><thead><tr><th>Código</th><th>Cuenta</th><th>Tipo</th><th>Compras</th><th>Estado</th><th>Acciones</th></tr></thead><tbody id="accountRows"><?php foreach($accounts as $a):?><tr data-type="<?=ccH($a['tipo'])?>" data-state="<?=ccH($a['activo'])?>"><td><strong><?=ccH($a['codigo'])?></strong></td><td><strong><?=ccH($a['nombre'])?></strong><?php if($a['sinopsis']):?><br><small><?=ccH($a['sinopsis'])?></small><?php endif;?></td><td><span class="badge"><?=ccH($a['tipo'])?></span></td><td><span class="badge <?=!empty($a['permite_compras'])?'on':'off'?>"><?=!empty($a['permite_compras'])?'Sí':'No'?></span></td><td><span class="badge <?=!empty($a['activo'])?'on':'off'?>"><?=!empty($a['activo'])?'Activa':'Inactiva'?></span></td><td><div class="actions" style="margin:0"><a class="btn tiny" href="?edit=<?=$a['id']?>"><i class="fa-solid fa-pen"></i></a><form method="post"><input type="hidden" name="csrf_token" value="<?=ccH($csrf)?>"><input type="hidden" name="action" value="toggle"><input type="hidden" name="id" value="<?=$a['id']?>"><button class="btn tiny secondary" title="Activar/desactivar"><i class="fa-solid fa-power-off"></i></button></form></div></td></tr><?php endforeach;?></tbody></table></div></section></div></main><script>function filterRows(){const q=document.getElementById('search').value.toLocaleLowerCase('es'),t=document.getElementById('type').value,s=document.getElementById('state').value;document.querySelectorAll('#accountRows tr').forEach(r=>r.style.display=(!q||r.textContent.toLocaleLowerCase('es').includes(q))&&(!t||r.dataset.type===t)&&(!s||r.dataset.state===s)?'':'none')}document.querySelectorAll('#search,#type,#state').forEach(e=>e.addEventListener(e.tagName==='INPUT'?'input':'change',filterRows));</script></body></html>
