<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Compras A/B/C | Acción Honduras</title>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
<link href="https://unpkg.com/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet">
<script src="https://unpkg.com/jquery@3.7.0/dist/jquery.min.js"></script>
<script src="https://unpkg.com/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<link rel="stylesheet" href="assets/css/compras.css">
</head>
<body>
<?php include 'sidebar.php'; ?>
<main class="main-wrapper">
<div class="page-header">
    <h1><i class="fa-solid fa-cart-flatbed"></i> Expediente de compra <?= $id?'#AH-C-'.sprintf('%04d',$id):'(Nuevo)' ?></h1>
    <div class="toolbar">
        <?php if($purchase): ?><span class="status-badge active"><?= h($purchase['estado']) ?></span><a class="btn blue" href="imprimir_compra.php?id=<?=$id?>" target="_blank"><i class="fa-solid fa-print"></i> Documentos</a><?php endif; ?>
        <a class="btn" href="mis_compras.php"><i class="fa-solid fa-clock-rotate-left"></i> Historial</a>
        <a class="btn" href="<?=h($self)?>"><i class="fa-solid fa-plus"></i> Nueva compra</a>
    </div>
</div>

<?= $msg ?>
<?php if($locked): ?><div class="locked-note"><i class="fa-solid fa-lock"></i> Expediente autorizado: se muestra en modo visor y no admite cambios.</div><?php endif; ?>
<?php if($schemaPending && !$schemaUpgradeRequested): ?>
<div class="schema-status" title="La actualización automática fue desactivada para evitar errores de espacio temporal del servidor.">
    <i class="fa-solid fa-shield-halved"></i>
    <span><strong>Modo estable:</strong> no se ejecutan cambios de estructura durante la carga.</span>
</div>
<?php endif; ?>

<div class="format-card">
    <div class="format-picker">
        <div class="format-icon"><i class="fa-solid fa-file-invoice-dollar"></i></div>
        <div class="format-field">
            <label>Formato de compra</label>
            <select id="formatSelectorTop" class="form-control format-select" <?=($purchase&&$rank>1)?'disabled':''?>>
                <option value="A" <?=$format==='A'?'selected':''?>>Forma A · Compra directa</option>
                <option value="B" <?=$format==='B'?'selected':''?>>Forma B · Comparación de cotizaciones</option>
                <option value="C" <?=$format==='C'?'selected':''?>>Forma C · Compra/pago con planillas</option>
            </select>
        </div>
    </div>
    <div class="format-explain" id="formatExplanation"></div>
</div>

<?php if($nombre_poa_vigente==='Ninguno'): ?><div class="alert error"><i class="fa-solid fa-triangle-exclamation"></i> No existe un POA activo. La solicitud puede elaborarse, pero no podrá imputarse ni autorizarse.</div><?php else: ?><div class="readonly-data"><i class="fa-solid fa-bullseye"></i> POA activo: <strong><?=h($nombre_poa_vigente)?></strong></div><?php endif; ?>

<div class="wizard-tabs">
<button class="tab-btn <?=$activeTab==='solicitud'?'active':''?>" onclick="navTab('solicitud',this)"><i class="fa-regular fa-file-lines"></i><span>1. Solicitud</span></button>
<?php if($format==='B'): ?><button class="tab-btn <?=$activeTab==='cotizaciones'?'active':''?>" onclick="navTab('cotizaciones',this)" <?=!$purchase?'disabled':''?>><i class="fa-solid fa-scale-balanced"></i><span>2. Cotizaciones</span></button><?php endif; ?>
<button class="tab-btn <?=$activeTab==='orden'?'active':''?>" onclick="navTab('orden',this)" <?=!$purchase?'disabled':''?>><i class="fa-solid fa-cart-shopping"></i><span><?=$format==='B'?'3':'2'?>. Orden</span></button>
<?php if($format==='C'): ?><button class="tab-btn <?=$activeTab==='planillas'?'active':''?>" onclick="navTab('planillas',this)" <?=!$purchase?'disabled':''?>><i class="fa-solid fa-people-group"></i><span>3. Planillas</span></button><?php endif; ?>
<button class="tab-btn <?=$activeTab==='transferencia'?'active':''?>" onclick="navTab('transferencia',this)" <?=!$purchase?'disabled':''?>><i class="fa-solid fa-chart-pie"></i><span>Imputación POA</span></button>
<button class="tab-btn <?=$activeTab==='autorizacion'?'active':''?>" onclick="navTab('autorizacion',this)" <?=!$purchase?'disabled':''?>><i class="fa-solid fa-signature"></i><span>Autorización</span></button>
<button class="tab-btn <?=$activeTab==='almacen'?'active':''?>" onclick="navTab('almacen',this)" <?=!$purchase?'disabled':''?>><i class="fa-solid fa-warehouse"></i><span>Almacén</span></button>
</div>

<!-- SOLICITUD -->
<section id="tab-solicitud" class="tab-panel <?=$activeTab==='solicitud'?'active':''?>">
<form method="post" id="formSolicitud">
<input type="hidden" name="csrf_token" value="<?=h(csrfToken())?>"><input type="hidden" name="action" value="guardar_solicitud"><input type="hidden" name="compra_id" value="<?=$id?>"><input type="hidden" name="formato_compra" id="formatHidden" value="<?=h($format)?>">
<h3 class="section-title">Información general</h3>
<div class="grid-2"><div class="form-group"><label>Fecha</label><input class="form-control" type="date" name="fecha" value="<?=h($purchase['fecha']??date('Y-m-d'))?>" required <?=$locked?'disabled':''?>></div><div class="form-group"><label>Solicitante</label><select class="form-control select2" name="solicitante" required <?=$locked?'disabled':''?>><option value="">Buscar empleado...</option><?php foreach($empleados as $emp): ?><option value="<?=h($emp)?>" <?=($purchase['solicitante']??'')===$emp?'selected':''?>><?=h($emp)?></option><?php endforeach; ?></select></div></div>
<div class="form-group"><label>Justificación / descripción</label><textarea class="form-control" rows="3" name="descripcion_actividad" required <?=$locked?'readonly':''?>><?=h($purchase['descripcion_actividad']??'')?></textarea></div>
<h3 class="section-title">Firmas para impresión</h3>
<div class="signature-box"><div class="grid-2"><div class="form-group"><label>Visto bueno</label><select class="form-control select2" name="visto_bueno" <?=$locked?'disabled':''?>><?php foreach($empleados as $emp): ?><option value="<?=h($emp)?>" <?=$valVb===$emp?'selected':''?>><?=h($emp)?></option><?php endforeach; ?></select></div><div class="form-group"><label>Firma autorizada</label><select class="form-control select2" name="firma_autoriza" <?=$locked?'disabled':''?>><?php foreach($empleados as $emp): ?><option value="<?=h($emp)?>" <?=$valFirma===$emp?'selected':''?>><?=h($emp)?></option><?php endforeach; ?></select></div></div><div class="grid-3"><div class="form-group"><label>Revisado por</label><select class="form-control select2" name="revisado_por" <?=$locked?'disabled':''?>><?php foreach($revisado_opts as $emp): ?><option value="<?=h($emp)?>" <?=$valRev===$emp?'selected':''?>><?=h($emp)?></option><?php endforeach; ?></select></div><div class="form-group"><label>Titular nivel 1</label><select class="form-control select2" name="titular_1" <?=$locked?'disabled':''?>><?php foreach($titulares_opts as $emp): ?><option value="<?=h($emp)?>" <?=$valT1===$emp?'selected':''?>><?=h($emp)?></option><?php endforeach; ?></select></div><div class="form-group"><label>Titular nivel 2</label><select class="form-control select2" name="titular_2" <?=$locked?'disabled':''?>><?php foreach($titulares_opts as $emp): ?><option value="<?=h($emp)?>" <?=$valT2===$emp?'selected':''?>><?=h($emp)?></option><?php endforeach; ?></select></div></div></div>
<h3 class="section-title">Artículos, servicios o insumos</h3>
<div class="table-wrap"><table class="dynamic-table"><thead><tr><th style="width:100px">Cantidad</th><th style="width:170px">Presentación</th><th>Artículo / servicio</th><th>Características</th><?php if(!$locked):?><th style="width:45px"></th><?php endif;?></tr></thead><tbody id="itemsBody"><?php foreach($details as $i=>$d): ?><tr><input type="hidden" name="items[<?=$i?>][id]" value="<?=$d['id']?>"><td><input type="number" step="0.01" min="0.01" name="items[<?=$i?>][cantidad]" value="<?=h($d['cantidad'])?>" required <?=$locked?'disabled':''?>></td><td><select class="select2-tags" name="items[<?=$i?>][presentacion]" <?=$locked?'disabled':''?>><?php foreach(array_unique(array_merge($presentaciones,[$d['presentacion']])) as $p):?><option value="<?=h($p)?>" <?=$d['presentacion']===$p?'selected':''?>><?=h($p)?></option><?php endforeach;?></select></td><td><input name="items[<?=$i?>][articulo]" value="<?=h($d['articulo'])?>" required <?=$locked?'disabled':''?>></td><td><input name="items[<?=$i?>][caracteristicas]" value="<?=h($d['caracteristicas'])?>" <?=$locked?'disabled':''?>></td><?php if(!$locked):?><td><button type="button" class="btn danger small" onclick="this.closest('tr').remove()"><i class="fa-solid fa-trash"></i></button></td><?php endif;?></tr><?php endforeach;?></tbody></table></div>
<?php if(!$locked):?><button type="button" class="btn" style="margin-top:12px" onclick="addItemRow()"><i class="fa-solid fa-plus"></i> Añadir fila</button><button class="btn-submit"><i class="fa-solid fa-floppy-disk"></i> Guardar solicitud y continuar</button><?php endif;?>
</form></section>

<?php if($purchase && $format==='B'): ?>
<!-- COTIZACIONES B -->
<section id="tab-cotizaciones" class="tab-panel <?=$activeTab==='cotizaciones'?'active':''?>">
<form method="post" id="formQuotes"><input type="hidden" name="csrf_token" value="<?=h(csrfToken())?>"><input type="hidden" name="action" value="guardar_cotizaciones"><input type="hidden" name="compra_id" value="<?=$id?>">
<div class="format-b-panel"><strong><i class="fa-solid fa-scale-balanced"></i> Forma B:</strong> compara hasta cuatro proveedores, siguiendo el formato institucional. El primer proveedor queda marcado como ganador inicial. Puede cambiar el ganador antes de guardar. Las filas extras permiten registrar artículos que solo cotizó otro proveedor, sin obligar a incluirlos en la orden del ganador.<?php if(!$quotes_component_db_ready): ?><div style="margin-top:8px;font-size:.78rem;color:#166534"><i class="fa-solid fa-shield-halved"></i> Almacenamiento alternativo activo: las cotizaciones se guardarán sin depender de tablas auxiliares.</div><?php endif; ?></div>
<h3 class="section-title">Proveedores consultados</h3><div class="provider-grid" id="providersGrid">
<?php for($p=1;$p<=4;$p++): $q=$quotes[$p-1]??[]; ?>
<div class="provider-card <?=!empty($q['es_ganador'])||(!$quotes&&$p===1)?'winner':''?>" data-provider-pos="<?=$p?>"><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:8px"><strong>Proveedor <?=$p?></strong><label class="winner-chip"><input type="radio" name="ganador_posicion" value="<?=$p?>" <?=(!empty($q['es_ganador'])||(!$quotes&&$p===1))?'checked':''?> <?=$locked?'disabled':''?>> Ganador</label></div><div class="form-group"><label>Proveedor</label><select class="form-control provider-search provider-select" name="cotizaciones[<?=$p-1?>][proveedor]" <?=$locked?'disabled':''?>><option value=""></option><option value="__CREATE_PROVIDER__">➕ Crear nuevo proveedor</option><?php foreach($proveedores_db as $prov):?><option value="<?=h($prov['nombre'])?>" <?=($q['proveedor']??'')===$prov['nombre']?'selected':''?>><?=h($prov['nombre'])?></option><?php endforeach;?></select></div><div class="grid-2"><div class="form-group"><label>RTN</label><input class="form-control" name="cotizaciones[<?=$p-1?>][rtn]" value="<?=h($q['rtn']??'')?>" <?=$locked?'disabled':''?>></div><div class="form-group"><label>Estado</label><select class="form-control" name="cotizaciones[<?=$p-1?>][estado]" <?=$locked?'disabled':''?>><option <?=($q['estado_cotizacion']??'Cotizó')==='Cotizó'?'selected':''?>>Cotizó</option><option <?=($q['estado_cotizacion']??'')==='No cotizó'?'selected':''?>>No cotizó</option><option <?=($q['estado_cotizacion']??'')==='No respondió'?'selected':''?>>No respondió</option></select></div></div><div class="provider-mini-info" data-provider-info><span><i class="fa-solid fa-location-dot"></i> <b data-field="direccion">—</b></span><span><i class="fa-solid fa-building-columns"></i> <b data-field="banco">—</b></span><span><i class="fa-solid fa-money-bill-transfer"></i> <b data-field="tipo_transferencia">—</b></span></div><div class="form-group"><label>Descuento</label><input class="form-control quote-discount" type="number" step="0.01" min="0" name="cotizaciones[<?=$p-1?>][descuento]" value="<?=h($q['descuento']??0)?>" <?=$locked?'disabled':''?>></div></div>
<?php endfor;?></div>
<h3 class="section-title">Resumen comparativo de cotizaciones</h3>
<div class="table-wrap"><table class="dynamic-table quote-table quote-table-four" id="quoteTable"><thead><tr><th>#</th><th>Cantidad</th><th>Presentación</th><th class="item-col">Artículo / insumo</th><th class="item-col">Características</th><?php for($p=1;$p<=4;$p++):?><th colspan="3" class="provider-head">Proveedor <?=$p?></th><?php endfor;?><?php if(!$locked):?><th></th><?php endif;?></tr><tr><th colspan="5"></th><?php for($p=1;$p<=4;$p++):?><th>Unitario</th><th>Total</th><th>G/E</th><?php endfor;?><?php if(!$locked):?><th></th><?php endif;?></tr></thead><tbody id="summaryBody">
<?php foreach($summaryRows as $rIndex=>$row): ?><tr><input type="hidden" name="resumen[<?=$rIndex?>][id]" value="<?=$row['id']?>"><input type="hidden" name="resumen[<?=$rIndex?>][es_extra]" value="<?=$row['es_extra']?>"><td><?=($rIndex+1)?></td><td><input type="number" step="0.01" name="resumen[<?=$rIndex?>][cantidad]" value="<?=h($row['cantidad'])?>" <?=$locked?'disabled':''?>></td><td><input name="resumen[<?=$rIndex?>][presentacion]" value="<?=h($row['presentacion'])?>" <?=$locked?'disabled':''?>></td><td><input name="resumen[<?=$rIndex?>][articulo]" value="<?=h($row['articulo'])?>" <?=$locked?'disabled':''?>></td><td><input name="resumen[<?=$rIndex?>][caracteristicas]" value="<?=h($row['caracteristicas'])?>" <?=$locked?'disabled':''?>></td><?php for($p=1;$p<=4;$p++): $quoteId=$quotes[$p-1]['id']??0; $pr=$prices[$row['id']][$quoteId]??[]; ?><td><input class="quote-price quote-unit" type="number" step="0.01" min="0" name="resumen[<?=$rIndex?>][precios][<?=$p?>][precio]" value="<?=h($pr['precio_unitario']??0)?>" <?=$locked?'disabled':''?>></td><td class="quote-total">L. <span class="quote-row-total"><?=number_format((float)($pr['precio_total']??0),2)?></span></td><td><select name="resumen[<?=$rIndex?>][precios][<?=$p?>][impuesto]" <?=$locked?'disabled':''?>><option value="E" <?=($pr['tipo_impuesto']??'E')==='E'?'selected':''?>>E</option><option value="G" <?=($pr['tipo_impuesto']??'')==='G'?'selected':''?>>G</option></select></td><?php endfor;?><?php if(!$locked):?><td><button type="button" class="btn danger small" onclick="this.closest('tr').remove();reindexSummary()"><i class="fa-solid fa-trash"></i></button></td><?php endif;?></tr><?php endforeach;?></tbody><tfoot><tr><th colspan="5">Totales</th><?php for($p=1;$p<=4;$p++):?><th colspan="3"><div id="providerTotal<?=$p?>">L. <?=number_format((float)($quotes[$p-1]['total']??0),2)?></div></th><?php endfor;?><?php if(!$locked):?><th></th><?php endif;?></tr></tfoot></table></div>
<?php if(!$locked):?><button type="button" class="btn" style="margin-top:12px" onclick="addSummaryRow(true)"><i class="fa-solid fa-plus"></i> Añadir fila extra al resumen</button><?php endif;?>
<div class="grid-2" style="margin-top:15px"><div class="form-group"><label>Observación / justificación del ganador</label><textarea class="form-control" rows="4" name="observacion_cotizacion" <?=$locked?'readonly':''?>><?=h($purchase['observacion_cotizacion']??'')?></textarea></div><div class="form-group"><label>Fecha de análisis</label><input class="form-control" type="date" name="fecha_analisis_cotizacion" value="<?=h($purchase['fecha_analisis_cotizacion']??date('Y-m-d'))?>" <?=$locked?'disabled':''?>><small style="color:#64748b">La observación debe dejar expresamente consignado el proveedor ganador y el criterio de selección.</small></div></div>
<?php if(!$locked):?><button class="btn-submit"><i class="fa-solid fa-scale-balanced"></i> Guardar resumen y generar orden del ganador</button><?php endif;?></form></section>
<?php endif;?>

<?php if($purchase): ?>
<!-- ORDEN -->
<section id="tab-orden" class="tab-panel <?=$activeTab==='orden'?'active':''?>"><form method="post"><input type="hidden" name="csrf_token" value="<?=h(csrfToken())?>"><input type="hidden" name="action" value="guardar_orden"><input type="hidden" name="compra_id" value="<?=$id?>">
<h3 class="section-title">Proveedor y valorización <?= $format==='B'?'del ganador':'' ?></h3>
<?php if($format==='B'): $winner=$winnerQuote; ?><div class="readonly-data"><i class="fa-solid fa-trophy"></i> Ganador: <strong><?=h($winner['proveedor']??'Pendiente de selección')?></strong>. Los precios se toman del resumen comparativo y no se duplican manualmente.</div><input type="hidden" name="descuento_total" value="<?=h($winner['descuento']??0)?>">
<?php else:?>
<div class="provider-picker-row"><div class="form-group"><label>Proveedor</label><div class="provider-select-actions"><select class="form-control provider-search" name="proveedor" id="providerSelect" required <?=$locked?'disabled':''?>><option value=""></option><option value="__CREATE_PROVIDER__">➕ Crear nuevo proveedor</option><?php foreach($proveedores_db as $prov):?><option value="<?=h($prov['nombre'])?>" <?=($purchase['proveedor']??'')===$prov['nombre']?'selected':''?>><?=h($prov['nombre'])?></option><?php endforeach;?></select><?php if(!$locked):?><button type="button" class="btn provider-new-btn" onclick="openProviderModal(document.getElementById('providerSelect'))"><i class="fa-solid fa-user-plus"></i> Nuevo</button><?php endif;?></div></div><div class="form-group"><label>RTN</label><input class="form-control" name="rtn" id="providerRtn" value="<?=h($purchase['rtn']??'')?>" <?=$locked?'disabled':''?>></div></div>
<div class="provider-info-card"><div class="provider-info-title"><i class="fa-solid fa-building-circle-check"></i><div><strong>Información del proveedor</strong><span>Se completa automáticamente al elegirlo.</span></div></div><div class="provider-info-grid"><div><small>Dirección</small><strong id="providerInfoAddress">—</strong></div><div><small>Banco</small><strong id="providerInfoBank">—</strong></div><div><small>Transferencia</small><strong id="providerInfoTransfer">—</strong></div><div><small>Tipo de cuenta</small><strong id="providerInfoAccountType">—</strong></div><div><small>Número de cuenta</small><strong id="providerInfoAccount">—</strong></div></div></div>
<?php endif;?>
<div class="table-wrap"><table class="dynamic-table"><thead><tr><th>Cant.</th><th>Presentación</th><th>Artículo / servicio</th><th>Características</th><th>Impuesto</th><th>Precio unitario</th><th>Total fila</th></tr></thead><tbody><?php foreach($orderViewDetails as $d):?><tr><td><?=h($d['cantidad'])?></td><td><?=h($d['presentacion'])?></td><td><?=h($d['articulo'])?></td><td><?=h($d['caracteristicas'])?></td><td><select name="detalles[<?=$d['id']?>][tipo_impuesto]" class="order-tax" <?=$locked||$format==='B'?'disabled':''?>><option value="G" <?=$d['tipo_impuesto']==='G'?'selected':''?>>G 15%</option><option value="E" <?=$d['tipo_impuesto']==='E'?'selected':''?>>Exento</option></select></td><td><input class="order-price" data-qty="<?=h($d['cantidad'])?>" type="number" step="0.01" min="0" name="detalles[<?=$d['id']?>][precio]" value="<?=h($d['precio_unitario'])?>" <?=$locked||$format==='B'?'disabled':''?>></td><td class="order-row-total">L. <?=number_format((float)$d['precio_total'],2)?></td></tr><?php endforeach;?></tbody></table></div>
<div class="totals-panel" style="margin-top:15px"><div class="totals-row"><span>Subtotal</span><strong id="orderSubtotal">L. <?=number_format($orderViewSubtotal,2)?></strong></div><div class="totals-row"><span>Descuento</span><?php if($format==='B'):?><strong>L. <?=number_format((float)($winner['descuento']??0),2)?></strong><?php else:?><input id="orderDiscount" class="form-control" style="max-width:170px;text-align:right" type="number" step="0.01" min="0" name="descuento_total" value="<?=h($orderViewDiscount)?>" <?=$locked?'disabled':''?>><?php endif;?></div><div class="totals-row"><span>ISV</span><strong id="orderTax">L. <?=number_format($orderViewTax,2)?></strong></div><div class="totals-row grand"><span>Total</span><strong id="orderGrand">L. <?=number_format($orderViewGrand,2)?></strong></div></div>
<?php if(!$locked):?><button class="btn-submit"><i class="fa-solid fa-calculator"></i> <?= $format==='B'?'Confirmar orden del ganador':'Guardar orden y continuar' ?></button><?php endif;?></form></section>

<?php if($format==='C'): ?>
<!-- PLANILLAS C -->
<section id="tab-planillas" class="tab-panel <?=$activeTab==='planillas'?'active':''?>"><form method="post" id="planillasForm"><input type="hidden" name="csrf_token" value="<?=h(csrfToken())?>"><input type="hidden" name="action" value="guardar_planillas"><input type="hidden" name="compra_id" value="<?=$id?>">
<div class="readonly-data"><strong><i class="fa-solid fa-users-rectangle"></i> Forma C:</strong> permite una o varias planillas. COMISAL aplica 4% de comisión por defecto; Nuevo Amanecer inicia sin comisión. Cada beneficiario generará su recibo individual en el visor de documentos.</div>
<div id="planillasContainer"></div><?php if(!$locked):?><button type="button" class="btn" onclick="addPlanilla()"><i class="fa-solid fa-plus"></i> Añadir planilla</button><button class="btn-submit"><i class="fa-solid fa-users"></i> Guardar planillas y continuar</button><?php endif;?></form></section>
<?php endif;?>

<!-- IMPUTACIÓN -->
<section id="tab-transferencia" class="tab-panel <?=$activeTab==='transferencia'?'active':''?>"><form method="post" id="poaForm"><input type="hidden" name="csrf_token" value="<?=h(csrfToken())?>"><input type="hidden" name="action" value="guardar_transferencia"><input type="hidden" name="compra_id" value="<?=$id?>">
<h3 class="section-title">Información del proveedor</h3><div class="provider-banking-shell"><div class="form-group provider-address-field"><label>Dirección</label><textarea class="form-control" rows="2" name="direccion_proveedor" id="providerAddressInput" <?=$locked?'readonly':''?>><?=h($providerAddressValue)?></textarea></div><div class="grid-4"><div class="form-group"><label>Banco</label><select class="form-control select2" name="banco" id="bankSelect" <?=$locked?'disabled':''?>><option value=""></option><?php foreach($bancos as $b):?><option value="<?=h($b)?>" <?=$providerBankValue===$b?'selected':''?>><?=h($b)?></option><?php endforeach;?></select></div><div class="form-group"><label>Tipo de transferencia</label><select class="form-control select2" name="tipo_transferencia" id="transferTypeSelect" <?=$locked?'disabled':''?>><option value=""></option><?php foreach($tipos_transferencia as $t):?><option value="<?=h($t)?>" <?=$providerTransferValue===$t?'selected':''?>><?=h($t)?></option><?php endforeach;?></select></div><div class="form-group"><label>Tipo de cuenta</label><select class="form-control select2" name="tipo_cuenta" id="accountTypeSelect" <?=$locked?'disabled':''?>><option value=""></option><?php foreach($tipos_cuenta as $t):?><option value="<?=h($t)?>" <?=$providerAccountTypeValue===$t?'selected':''?>><?=h($t)?></option><?php endforeach;?></select></div><div class="form-group"><label>Mes de ejecución</label><select class="form-control" name="mes_ejecucion" id="executionMonthSelect" <?=$locked?'disabled':''?>><?php foreach(['jul'=>'Jul','aug'=>'Ago','sep'=>'Sep','oct'=>'Oct','nov'=>'Nov','dec'=>'Dic','jan'=>'Ene','feb'=>'Feb','mar'=>'Mar','apr'=>'Abr','may'=>'May','jun'=>'Jun'] as $m=>$label):?><option value="<?=$m?>" <?=($purchase['mes_ejecucion']??monthKeyFromDate($purchase['fecha']))===$m?'selected':''?>><?=$label?></option><?php endforeach;?></select><div class="execution-month-note"><i class="fa-solid fa-table-cells"></i> Al autorizar, el monto se registrará en la columna <strong>Eje.</strong> de este mes en el POA.</div></div></div><div class="form-group"><label>Número de cuenta bancaria</label><input class="form-control" name="cuenta_bancaria" id="accountNumberInput" value="<?=h($providerAccountValue)?>" <?=$locked?'disabled':''?>></div></div>
<h3 class="section-title">Imputación presupuestaria (POA)</h3><div class="summary-box"><div><small>Monto de la orden</small><strong>L. <?=number_format((float)$purchase['monto_total'],2)?></strong></div><div style="text-align:right"><small>Total distribuido</small><strong id="poaAssigned">L. 0.00</strong></div></div>
<div class="table-wrap poa-imputation-wrap"><table class="dynamic-table poa-imputation-table"><thead><tr><th class="poa-line-col">Línea POA</th><th class="poa-account-col">Cuenta contable financiera</th><th class="poa-amount-col">Monto a imputar (L.)</th><?php if(!$locked):?><th class="poa-action-col"></th><?php endif;?></tr></thead><tbody id="poaBody"><?php foreach($poaDistribution as $i=>$pd): $compactLabel=compactPoaLabel($pd['marco_logico']??'', $pd['ext']??''); ?><tr><td><select class="form-control select2-poa" name="poa_lineas[<?=$i?>][hash]" <?=$locked?'disabled':''?>><option value="<?=h($pd['poa_hash'])?>" selected><?=h($compactLabel)?></option><?=$poaOptions?></select></td><td><select class="form-control select2-account" name="poa_lineas[<?=$i?>][cuenta_id]" required <?=$locked?'disabled':''?>><option value="">Seleccione del catálogo…</option><?php foreach($catalogo_cuentas as $account):?><option value="<?=$account['id']?>" <?=((int)($pd['catalogo_cuenta_id']??0)===(int)$account['id'])?'selected':''?>><?=h(accountingCatalogLabel($account))?></option><?php endforeach;?></select><?php if($locked&&!empty($pd['cuenta_contable'])):?><small><?=h($pd['cuenta_contable'])?></small><?php endif;?></td><td><input class="poa-amount" type="number" step="0.01" min="0" name="poa_lineas[<?=$i?>][monto]" value="<?=h($pd['monto'])?>" <?=$locked?'disabled':''?>></td><?php if(!$locked):?><td><button type="button" class="btn danger small" onclick="this.closest('tr').remove();calcPoaTotal()" title="Eliminar línea"><i class="fa-solid fa-trash"></i></button></td><?php endif;?></tr><?php endforeach;?></tbody></table></div><?php if(!$locked):?><div class="poa-actions"><button type="button" class="btn" onclick="addPoaRow()"><i class="fa-solid fa-plus"></i> Añadir línea</button><button class="btn-submit poa-save-btn"><i class="fa-solid fa-building-columns"></i> Guardar imputación y reservar fondos</button></div><?php endif;?></form></section>

<!-- AUTORIZACIÓN -->
<section id="tab-autorizacion" class="tab-panel <?=$activeTab==='autorizacion'?'active':''?>"><div class="readonly-data"><strong>Autorización idempotente:</strong> una recarga, doble clic o reenvío no podrá ejecutar dos veces la misma compra. El gasto se aplicará al mes <strong><?=strtoupper(h($purchase['mes_ejecucion']??monthKeyFromDate($purchase['fecha'])))?></strong>.</div><h3 class="section-title">Resumen de ejecución</h3><div class="table-wrap"><table class="dynamic-table"><thead><tr><th>Línea POA</th><th>Cuenta contable</th><th>Monto</th></tr></thead><tbody><?php foreach($poaDistribution as $pd):?><tr><td><strong><?=h(compactPoaLabel($pd['marco_logico']??'', $pd['ext']??''))?></strong></td><td><?=h($pd['cuenta_contable'])?></td><td>L. <?=number_format((float)$pd['monto'],2)?></td></tr><?php endforeach;?></tbody></table></div><?php if(!$locked):?><form method="post" onsubmit="return confirm('¿Autorizar y ejecutar definitivamente esta compra?')"><input type="hidden" name="csrf_token" value="<?=h(csrfToken())?>"><input type="hidden" name="action" value="autorizar_pago"><input type="hidden" name="compra_id" value="<?=$id?>"><button class="btn-submit" style="background:#34859B;padding:18px"><i class="fa-solid fa-signature"></i> Autorizar pago y ejecutar POA</button></form><?php else:?><div class="alert success">Autorizado por <?=h($purchase['autorizado_por'])?> el <?=h($purchase['fecha_autorizacion'])?></div><?php endif;?></section>

<!-- ALMACÉN -->
<section id="tab-almacen" class="tab-panel <?=$activeTab==='almacen'?'active':''?>"><h3 class="section-title">Recepción de bienes o cierre del servicio</h3><form method="post"><input type="hidden" name="csrf_token" value="<?=h(csrfToken())?>"><input type="hidden" name="action" value="recibir_almacen"><input type="hidden" name="compra_id" value="<?=$id?>"><div class="grid-3"><div class="form-group"><label>Fecha recepción</label><input class="form-control" type="date" name="fecha_recepcion" value="<?=h($purchase['fecha_recepcion']??date('Y-m-d'))?>" <?=$rank>=6?'disabled':''?>></div><div class="form-group"><label>Recibido por</label><input class="form-control" name="recibido_por" value="<?=h($purchase['recibido_por']??'')?>" <?=$rank>=6?'disabled':''?>></div><div class="form-group"><label>Notas generales</label><input class="form-control" name="notas_recepcion" value="<?=h($purchase['notas_recepcion']??'')?>" <?=$rank>=6?'disabled':''?>></div></div><div class="table-wrap"><table class="dynamic-table"><thead><tr><th>Artículo / servicio</th><th>Ordenado</th><th>Recibido</th><th>Dañado / faltante</th><th>Observación</th></tr></thead><tbody><?php foreach($details as $d): $r=$receipts[$d['id']]??[];?><tr><td><?=h($d['articulo'])?></td><td><?=h($d['cantidad'])?></td><td><input type="number" step="0.01" min="0" name="recepcion[<?=$d['id']?>][recibida]" value="<?=h($r['cantidad_recibida']??$d['cantidad'])?>" <?=$rank>=6?'disabled':''?>></td><td><input type="number" step="0.01" min="0" name="recepcion[<?=$d['id']?>][danada]" value="<?=h($r['cantidad_danada']??0)?>" <?=$rank>=6?'disabled':''?>></td><td><input name="recepcion[<?=$d['id']?>][observacion]" value="<?=h($r['observacion']??'')?>" <?=$rank>=6?'disabled':''?>></td></tr><?php endforeach;?></tbody></table></div><?php if($rank===5):?><button class="btn-submit"><i class="fa-solid fa-warehouse"></i> Registrar recepción y cerrar expediente</button><?php endif;?></form></section>
<?php endif; ?>
</main>

<!-- MODAL PROVEEDOR -->
<div id="providerModal" class="modal-overlay"><div class="modal-content provider-modal-content"><div class="modal-header"><div><strong><i class="fa-solid fa-building-user"></i> Registrar proveedor</strong><small>La información quedará disponible en todas las compras.</small></div><button type="button" class="btn small" onclick="closeProviderModal()">×</button></div><div class="modal-body"><div class="grid-2"><div class="form-group"><label>Nombre o razón social</label><input id="newProviderName" class="form-control"></div><div class="form-group"><label>RTN</label><input id="newProviderRtn" class="form-control" maxlength="30"></div></div><div class="form-group"><label>Dirección</label><textarea id="newProviderAddress" class="form-control" rows="3" placeholder="Municipio, colonia, barrio, calle, referencia..."></textarea></div><div class="grid-3"><div class="form-group"><label>Banco</label><select id="newProviderBank" class="form-control select2-modal"><option value=""></option><?php foreach($bancos as $b):?><option value="<?=h($b)?>"><?=h($b)?></option><?php endforeach;?></select></div><div class="form-group"><label>Tipo de transferencia</label><select id="newProviderTransfer" class="form-control select2-modal"><option value=""></option><?php foreach($tipos_transferencia as $t):?><option value="<?=h($t)?>"><?=h($t)?></option><?php endforeach;?></select></div><div class="form-group"><label>Tipo de cuenta</label><select id="newProviderType" class="form-control select2-modal"><option value=""></option><?php foreach($tipos_cuenta as $t):?><option value="<?=h($t)?>"><?=h($t)?></option><?php endforeach;?></select></div></div><div class="form-group"><label>Número de cuenta bancaria</label><input id="newProviderAccount" class="form-control"></div><div id="providerModalMessage" class="provider-modal-message"></div></div><div class="modal-footer"><button type="button" class="btn" onclick="closeProviderModal()">Cancelar</button><button type="button" class="btn primary" id="saveProviderBtn" onclick="saveProviderModal()"><i class="fa-solid fa-floppy-disk"></i> Guardar proveedor</button></div></div></div>

<?php require __DIR__ . '/partials/compras_scripts.php'; ?>
</body>
</html>
