<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/includes/bootstrap.php';
require_once dirname(__DIR__) . '/includes/FormService.php';
form_require_admin_auth($db);
form_assert_installed($db);
$service = new FormService($db);
$id=(int)($_GET['id']??0);
$schema=$service->getSchema($id);$form=$schema['form'];
$analytics=$service->analytics($id);$responses=$service->responseRows($id,20000);
$questions=[];foreach($schema['sections'] as $s)foreach($s['questions'] as $q)if($q['tipo']!=='title_description')$questions[(int)$q['id']]=$q;
$last=$responses[0]['submitted_at']??null;
?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Respuestas | <?=form_h($form['titulo'])?></title><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800;900&display=swap" rel="stylesheet"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"><link rel="stylesheet" href="../assets/formularios.css?v=20260714-3"><script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.2/dist/chart.umd.min.js"></script><script src="https://unpkg.com/xlsx@0.18.5/dist/xlsx.full.min.js"></script></head>
<body><div class="forms-shell"><?php $sidebar=__DIR__.'/sidebar.php';if(is_file($sidebar))include $sidebar; ?><main class="forms-main"><div class="forms-topbar"><div class="forms-title"><a href="formularios.php" style="color:#34859B;font-weight:800"><i class="fa-solid fa-arrow-left"></i> Formularios</a><h1><?=form_h($form['titulo'])?></h1><p>Resumen, gráficos y detalle completo de respuestas.</p></div><div style="display:flex;gap:8px;flex-wrap:wrap"><a class="btn" href="editor_formulario.php?id=<?=$id?>"><i class="fa-solid fa-pen"></i> Editar formulario</a><button id="exportXlsx" class="btn btn-green"><i class="fa-solid fa-file-excel"></i> Exportar XLSX</button></div></div>
<div class="metrics"><div class="card metric"><span>Respuestas</span><strong><?=number_format($analytics['total'])?></strong></div><div class="card metric"><span>Preguntas</span><strong><?=number_format(count($questions))?></strong></div><div class="card metric"><span>Última respuesta</span><strong style="font-size:1.05rem"><?=$last?form_h(date('d/m/Y H:i',strtotime($last))):'—'?></strong></div><div class="card metric"><span>Estado</span><strong style="font-size:1.05rem"><?=form_h(ucfirst($form['estado']))?></strong></div></div>
<div class="tabs" style="margin-top:20px"><a class="tab active" href="#resumen">Resumen</a><a class="tab" href="#individuales">Individuales</a><a class="tab" href="#tabla">Tabla</a></div>
<section id="resumen"><div class="card chart-card" style="margin-bottom:16px"><h3>Respuestas en el tiempo</h3><canvas id="timelineChart" height="85"></canvas></div><div class="chart-grid">
<?php foreach($analytics['questions'] as $stat): $type=$stat['tipo']; ?><article class="card chart-card"><h3><?=form_h($stat['titulo'])?></h3><div style="color:#64748b;font-size:.8rem;margin-bottom:10px"><?=number_format($stat['count'])?> respuestas<?php if(isset($stat['average'])): ?> · Promedio <?=number_format((float)$stat['average'],2)?><?php endif; ?></div><?php if(in_array($type,['multiple_choice','checkboxes','dropdown','linear_scale','rating','consent','geo_cascade','center_selector'],true) && $stat['values']): ?><canvas class="question-chart" data-labels='<?=form_h(form_json_encode(array_keys($stat['values'])))?>' data-values='<?=form_h(form_json_encode(array_values($stat['values'])))?>' height="210"></canvas><?php else: ?><div class="text-list"><?php foreach(array_slice(array_keys($stat['values']),0,100) as $text): ?><div class="text-answer"><?=form_h($text)?></div><?php endforeach; ?><?php if(!$stat['values']): ?><div class="text-answer" style="color:#94a3b8">Sin respuestas.</div><?php endif; ?></div><?php endif; ?></article><?php endforeach; ?></div></section>
<section id="individuales" style="display:none"><div class="responses-layout"><?php foreach($responses as $index=>$r): ?><article class="card" style="padding:18px"><h3 style="margin-top:0">Respuesta #<?=count($responses)-$index?> <small style="color:#64748b;font-size:.75rem"><?=form_h(date('d/m/Y H:i',strtotime($r['submitted_at'])))?></small></h3><?php if($r['correo']): ?><p><b>Correo:</b> <?=form_h($r['correo'])?></p><?php endif; ?><?php foreach($questions as $qid=>$q): $a=$r['answers'][$qid]??null; ?><div style="padding:10px 0;border-top:1px solid #edf1f5"><div style="font-weight:850;font-size:.84rem"><?=form_h($q['titulo'])?></div><div style="color:#536176;margin-top:5px"><?php if(!$a): ?>—<?php elseif($a['file']): ?><a style="color:#087a95" target="_blank" href="../<?=form_h($a['file'])?>">Ver archivo adjunto</a><?php elseif($a['json']): ?><?=form_h(is_array($a['json'])?implode(' · ',array_map(fn($v)=>is_array($v)?form_json_encode($v):(string)$v,$a['json'])):form_json_encode($a['json']))?><?php else: ?><?=nl2br(form_h((string)$a['text']))?><?php endif; ?></div></div><?php endforeach; ?></article><?php endforeach; ?><?php if(!$responses): ?><div class="card empty">Aún no hay respuestas.</div><?php endif; ?></div></section>
<section id="tabla" style="display:none"><div class="card table-wrap"><table class="responses-table" id="responsesTable"><thead><tr><th>#</th><th>Fecha</th><th>Correo</th><?php foreach($questions as $q): ?><th><?=form_h($q['titulo'])?></th><?php endforeach; ?></tr></thead><tbody><?php foreach($responses as $r): ?><tr><td><?=$r['id']?></td><td><?=form_h($r['submitted_at'])?></td><td><?=form_h((string)$r['correo'])?></td><?php foreach($questions as $qid=>$q): $a=$r['answers'][$qid]??null; ?><td><?php if(!$a): ?><?php elseif($a['file']): ?><?=form_h($a['file'])?><?php elseif($a['json']): ?><?=form_h(form_json_encode($a['json']))?><?php else: ?><?=form_h((string)$a['text'])?><?php endif; ?></td><?php endforeach; ?></tr><?php endforeach; ?></tbody></table></div></section>
</main></div>
<script>
const timeline=<?=form_json_encode($analytics['timeline'])?>;new Chart(document.getElementById('timelineChart'),{type:'line',data:{labels:Object.keys(timeline),datasets:[{label:'Respuestas',data:Object.values(timeline),tension:.25,fill:true}]},options:{responsive:true,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,ticks:{precision:0}}}}});
document.querySelectorAll('.question-chart').forEach((el,i)=>{const labels=JSON.parse(el.dataset.labels),values=JSON.parse(el.dataset.values);new Chart(el,{type:labels.length>7?'bar':'doughnut',data:{labels,datasets:[{data:values}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom'}}}});});
document.querySelectorAll('.tab').forEach(tab=>tab.onclick=e=>{e.preventDefault();document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));tab.classList.add('active');['resumen','individuales','tabla'].forEach(id=>document.getElementById(id).style.display='#'+id===tab.getAttribute('href')?'block':'none');});
document.getElementById('exportXlsx').onclick=()=>{const wb=XLSX.utils.book_new();const ws=XLSX.utils.table_to_sheet(document.getElementById('responsesTable'));XLSX.utils.book_append_sheet(wb,ws,'Respuestas');XLSX.writeFile(wb,<?=json_encode(form_slugify($form['titulo']).'-respuestas.xlsx')?>);};
</script></body></html>
